{
    "type": "bundle",
    "id": "bundle--dc3277bb-5ac0-4230-b101-12c16d3e02ca",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--29b90cfb-783b-40d0-9bf3-0168c1502d89",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2021-03-30T02:15:00.000Z",
            "modified": "2021-04-02T12:50:00.000Z",
            "name": "CVE-2018-1110",
            "description": "A flaw was found in knot-resolver before version 2.3.0. Malformed DNS messages may cause denial of service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2018-1110"
                },
                {
                    "source_name": "cwe",
                    "external_id": "CWE-20"
                },
                {
                    "source_name": "https://bugzilla.redhat.com/show_bug.cgi?id=1944328",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1944328"
                },
                {
                    "source_name": "https://www.knot-resolver.cz/2018-04-23-knot-resolver-2.3.0.html",
                    "url": "https://www.knot-resolver.cz/2018-04-23-knot-resolver-2.3.0.html"
                },
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b2b5f2cd-49e6-4091-a0e0-c0bb71543e23": {
                    "extension_type": "property-extension",
                    "nvd_cve": {
                        "data_type": "CVE",
                        "data_format": "MITRE",
                        "data_version": "4.0",
                        "CVE_data_meta": {
                            "ID": "CVE-2018-1110",
                            "ASSIGNER": "secalert@redhat.com"
                        },
                        "problemtype": {
                            "problemtype_data": [
                                {
                                    "description": [
                                        {
                                            "lang": "en",
                                            "value": "CWE-20"
                                        }
                                    ]
                                }
                            ]
                        },
                        "references": {
                            "reference_data": [
                                {
                                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1944328",
                                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1944328",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Issue Tracking",
                                        "Third Party Advisory"
                                    ]
                                },
                                {
                                    "url": "https://www.knot-resolver.cz/2018-04-23-knot-resolver-2.3.0.html",
                                    "name": "https://www.knot-resolver.cz/2018-04-23-knot-resolver-2.3.0.html",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Release Notes",
                                        "Vendor Advisory"
                                    ]
                                }
                            ]
                        },
                        "description": {
                            "description_data": [
                                {
                                    "lang": "en",
                                    "value": "A flaw was found in knot-resolver before version 2.3.0. Malformed DNS messages may cause denial of service."
                                }
                            ]
                        }
                    },
                    "impact": {
                        "baseMetricV3": {
                            "cvssV3": {
                                "version": "3.1",
                                "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                                "attackVector": "NETWORK",
                                "attackComplexity": "LOW",
                                "privilegesRequired": "NONE",
                                "userInteraction": "NONE",
                                "scope": "UNCHANGED",
                                "confidentialityImpact": "NONE",
                                "integrityImpact": "NONE",
                                "availabilityImpact": "HIGH",
                                "baseScore": 7.5,
                                "baseSeverity": "HIGH"
                            },
                            "exploitabilityScore": 3.9,
                            "impactScore": 3.6
                        },
                        "baseMetricV2": {
                            "cvssV2": {
                                "version": "2.0",
                                "vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
                                "accessVector": "NETWORK",
                                "accessComplexity": "LOW",
                                "authentication": "NONE",
                                "confidentialityImpact": "NONE",
                                "integrityImpact": "NONE",
                                "availabilityImpact": "PARTIAL",
                                "baseScore": 5.0
                            },
                            "severity": "MEDIUM",
                            "exploitabilityScore": 10.0,
                            "impactScore": 2.9,
                            "acInsufInfo": false,
                            "obtainAllPrivilege": false,
                            "obtainUserPrivilege": false,
                            "obtainOtherPrivilege": false,
                            "userInteractionRequired": false
                        }
                    },
                    "publishedDate": "2021-03-30T02:15Z",
                    "lastModifiedDate": "2021-04-02T12:50Z"
                }
            }
        },
        {
            "type": "indicator",
            "spec_version": "2.1",
            "id": "indicator--10a03f4b-c1ef-4b27-97da-e375c155e67b",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2021-03-30T02:15:00.000Z",
            "modified": "2021-04-02T12:50:00.000Z",
            "name": "CVE-2018-1110",
            "description": "A flaw was found in knot-resolver before version 2.3.0. Malformed DNS messages may cause denial of service.",
            "indicator_types": [
                "compromised"
            ],
            "pattern": "[(software:cpe='cpe:2.3:a:nic:knot_resolver:*:*:*:*:*:*:*:*')]",
            "pattern_type": "stix",
            "pattern_version": "2.1",
            "valid_from": "2021-03-30T02:15:00Z",
            "external_references": [
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b463c449-d022-48b7-b464-3e9c7ec5cf16": {
                    "extension_type": "property-extension",
                    "all_cpe23uris": [
                        "cpe:2.3:a:nic:knot_resolver:*:*:*:*:*:*:*:*"
                    ],
                    "vulnerable_cpeid": [
                        "cpe:2.3:a:nic:knot_resolver:*:*:*:*:*:*:*:*"
                    ]
                }
            }
        },
        {
            "type": "relationship",
            "spec_version": "2.1",
            "id": "relationship--5a7a3dae-2e0c-4d56-aaef-cdfbfb3770af",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2021-03-30T02:15:00.000Z",
            "modified": "2021-04-02T12:50:00.000Z",
            "relationship_type": "identifies",
            "source_ref": "indicator--10a03f4b-c1ef-4b27-97da-e375c155e67b",
            "target_ref": "vulnerability--29b90cfb-783b-40d0-9bf3-0168c1502d89",
            "external_references": [
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ]
        }
    ]
}