{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--39a46906-9657-4417-859e-3bc8130f93bd",
    "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
    "created": "2020-12-22T17:15:00.000Z",
    "modified": "2022-07-25T18:15:00.000Z",
    "name": "CVE-2020-29396",
    "description": "A sandboxing issue in Odoo Community 11.0 through 13.0 and Odoo Enterprise 11.0 through 13.0, when running with Python 3.6 or later, allows remote authenticated users to execute arbitrary code, leading to privilege escalation.",
    "external_references": [
        {
            "source_name": "cve",
            "external_id": "CVE-2020-29396"
        },
        {
            "source_name": "cwe",
            "external_id": "NVD-CWE-noinfo"
        },
        {
            "source_name": "https://github.com/odoo/odoo/issues/63712",
            "url": "https://github.com/odoo/odoo/issues/63712"
        },
        {
            "source_name": "N/A",
            "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
        },
        {
            "source_name": "cve2stix",
            "description": "This object was created using cve2stix from the Signals Corps.",
            "url": "https://github.com/signalscorps/cve2stix"
        }
    ],
    "object_marking_refs": [
        "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
    ],
    "extensions": {
        "extension-definition--b2b5f2cd-49e6-4091-a0e0-c0bb71543e23": {
            "extension_type": "property-extension",
            "impact": {
                "baseMetricV2": {
                    "acInsufInfo": false,
                    "cvssV2": {
                        "accessComplexity": "LOW",
                        "accessVector": "NETWORK",
                        "authentication": "SINGLE",
                        "availabilityImpact": "PARTIAL",
                        "baseScore": 6.5,
                        "confidentialityImpact": "PARTIAL",
                        "integrityImpact": "PARTIAL",
                        "vectorString": "AV:N/AC:L/Au:S/C:P/I:P/A:P",
                        "version": "2.0"
                    },
                    "exploitabilityScore": 8.0,
                    "impactScore": 6.4,
                    "obtainAllPrivilege": false,
                    "obtainOtherPrivilege": false,
                    "obtainUserPrivilege": false,
                    "severity": "MEDIUM",
                    "userInteractionRequired": false
                },
                "baseMetricV3": {
                    "cvssV3": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 8.8,
                        "baseSeverity": "HIGH",
                        "confidentialityImpact": "HIGH",
                        "integrityImpact": "HIGH",
                        "privilegesRequired": "LOW",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
                        "version": "3.1"
                    },
                    "exploitabilityScore": 2.8,
                    "impactScore": 5.9
                }
            },
            "lastModifiedDate": "2022-07-25T18:15Z",
            "nvd_cve": {
                "CVE_data_meta": {
                    "ASSIGNER": "security@odoo.com",
                    "ID": "CVE-2020-29396"
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "en",
                            "value": "A sandboxing issue in Odoo Community 11.0 through 13.0 and Odoo Enterprise 11.0 through 13.0, when running with Python 3.6 or later, allows remote authenticated users to execute arbitrary code, leading to privilege escalation."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "en",
                                    "value": "NVD-CWE-noinfo"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://github.com/odoo/odoo/issues/63712",
                            "url": "https://github.com/odoo/odoo/issues/63712",
                            "refsource": "MISC",
                            "tags": [
                                "Patch",
                                "Third Party Advisory"
                            ]
                        },
                        {
                            "name": "N/A",
                            "url": "https://www.oracle.com/security-alerts/cpujul2022.html",
                            "refsource": "N/A",
                            "tags": []
                        }
                    ]
                }
            },
            "publishedDate": "2020-12-22T17:15Z"
        }
    }
}