{
    "type": "bundle",
    "id": "bundle--26eb8e4a-c0e5-4ebd-8cf1-a3892e79c6b7",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--5b7c380b-5cb3-42dd-bf3e-07f1e31c539c",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-09-13T18:15:00.000Z",
            "modified": "2022-09-16T13:11:00.000Z",
            "name": "CVE-2022-36104",
            "description": "TYPO3 is an open source PHP based web content management system released under the GNU GPL. In affected versions requesting invalid or non-existing resources via HTTP triggers the page error handler which again could retrieve content to be shown as an error message from another page. This leads to a scenario in which the application is calling itself recursively - amplifying the impact of the initial attack until the limits of the web server are exceeded. Users are advised to update to TYPO3 version 11.5.16 to resolve this issue. There are no known workarounds for this issue.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-36104"
                },
                {
                    "source_name": "cwe",
                    "external_id": "CWE-770"
                },
                {
                    "source_name": "https://github.com/TYPO3/typo3/security/advisories/GHSA-fffr-7x4x-f98q",
                    "url": "https://github.com/TYPO3/typo3/security/advisories/GHSA-fffr-7x4x-f98q"
                },
                {
                    "source_name": "https://typo3.org/security/advisory/typo3-core-sa-2022-006",
                    "url": "https://typo3.org/security/advisory/typo3-core-sa-2022-006"
                },
                {
                    "source_name": "https://github.com/TYPO3/typo3/commit/179dd7cd78947081d573fee2050e197faa556f13",
                    "url": "https://github.com/TYPO3/typo3/commit/179dd7cd78947081d573fee2050e197faa556f13"
                },
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b2b5f2cd-49e6-4091-a0e0-c0bb71543e23": {
                    "extension_type": "property-extension",
                    "nvd_cve": {
                        "data_type": "CVE",
                        "data_format": "MITRE",
                        "data_version": "4.0",
                        "CVE_data_meta": {
                            "ID": "CVE-2022-36104",
                            "ASSIGNER": "security-advisories@github.com"
                        },
                        "problemtype": {
                            "problemtype_data": [
                                {
                                    "description": [
                                        {
                                            "lang": "en",
                                            "value": "CWE-770"
                                        }
                                    ]
                                }
                            ]
                        },
                        "references": {
                            "reference_data": [
                                {
                                    "url": "https://github.com/TYPO3/typo3/security/advisories/GHSA-fffr-7x4x-f98q",
                                    "name": "https://github.com/TYPO3/typo3/security/advisories/GHSA-fffr-7x4x-f98q",
                                    "refsource": "CONFIRM",
                                    "tags": [
                                        "Third Party Advisory"
                                    ]
                                },
                                {
                                    "url": "https://typo3.org/security/advisory/typo3-core-sa-2022-006",
                                    "name": "https://typo3.org/security/advisory/typo3-core-sa-2022-006",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Vendor Advisory"
                                    ]
                                },
                                {
                                    "url": "https://github.com/TYPO3/typo3/commit/179dd7cd78947081d573fee2050e197faa556f13",
                                    "name": "https://github.com/TYPO3/typo3/commit/179dd7cd78947081d573fee2050e197faa556f13",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Patch",
                                        "Third Party Advisory"
                                    ]
                                }
                            ]
                        },
                        "description": {
                            "description_data": [
                                {
                                    "lang": "en",
                                    "value": "TYPO3 is an open source PHP based web content management system released under the GNU GPL. In affected versions requesting invalid or non-existing resources via HTTP triggers the page error handler which again could retrieve content to be shown as an error message from another page. This leads to a scenario in which the application is calling itself recursively - amplifying the impact of the initial attack until the limits of the web server are exceeded. Users are advised to update to TYPO3 version 11.5.16 to resolve this issue. There are no known workarounds for this issue."
                                }
                            ]
                        }
                    },
                    "impact": {
                        "baseMetricV3": {
                            "cvssV3": {
                                "version": "3.1",
                                "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                                "attackVector": "NETWORK",
                                "attackComplexity": "LOW",
                                "privilegesRequired": "NONE",
                                "userInteraction": "NONE",
                                "scope": "UNCHANGED",
                                "confidentialityImpact": "NONE",
                                "integrityImpact": "NONE",
                                "availabilityImpact": "HIGH",
                                "baseScore": 7.5,
                                "baseSeverity": "HIGH"
                            },
                            "exploitabilityScore": 3.9,
                            "impactScore": 3.6
                        }
                    },
                    "publishedDate": "2022-09-13T18:15Z",
                    "lastModifiedDate": "2022-09-16T13:11Z"
                }
            }
        },
        {
            "type": "indicator",
            "spec_version": "2.1",
            "id": "indicator--4c6e90fa-c19f-49f1-8ad3-8e6db9b73e64",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-09-13T18:15:00.000Z",
            "modified": "2022-09-16T13:11:00.000Z",
            "name": "CVE-2022-36104",
            "description": "TYPO3 is an open source PHP based web content management system released under the GNU GPL. In affected versions requesting invalid or non-existing resources via HTTP triggers the page error handler which again could retrieve content to be shown as an error message from another page. This leads to a scenario in which the application is calling itself recursively - amplifying the impact of the initial attack until the limits of the web server are exceeded. Users are advised to update to TYPO3 version 11.5.16 to resolve this issue. There are no known workarounds for this issue.",
            "indicator_types": [
                "compromised"
            ],
            "pattern": "[(software:cpe='cpe:2.3:a:typo3:typo3:*:*:*:*:*:*:*:*')]",
            "pattern_type": "stix",
            "pattern_version": "2.1",
            "valid_from": "2022-09-13T18:15:00Z",
            "external_references": [
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b463c449-d022-48b7-b464-3e9c7ec5cf16": {
                    "extension_type": "property-extension",
                    "all_cpe23uris": [
                        "cpe:2.3:a:typo3:typo3:*:*:*:*:*:*:*:*"
                    ],
                    "vulnerable_cpeid": [
                        "cpe:2.3:a:typo3:typo3:*:*:*:*:*:*:*:*"
                    ]
                }
            }
        },
        {
            "type": "relationship",
            "spec_version": "2.1",
            "id": "relationship--e756146c-05c8-41ac-b5c4-7cad17e6744f",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-09-13T18:15:00.000Z",
            "modified": "2022-09-16T13:11:00.000Z",
            "relationship_type": "identifies",
            "source_ref": "indicator--4c6e90fa-c19f-49f1-8ad3-8e6db9b73e64",
            "target_ref": "vulnerability--5b7c380b-5cb3-42dd-bf3e-07f1e31c539c",
            "external_references": [
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ]
        }
    ]
}