{
    "type": "bundle",
    "id": "bundle--039c84a8-161c-4b4d-af19-b88bd7452078",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--c28fffa9-5b04-4569-932a-187e2dbfd848",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-11-18T22:15:00.000Z",
            "modified": "2022-11-20T02:44:00.000Z",
            "name": "CVE-2022-41899",
            "description": "TensorFlow is an open source platform for machine learning. Inputs `dense_features` or `example_state_data` not of rank 2 will trigger a `CHECK` fail in `SdcaOptimizer`. We have patched the issue in GitHub commit 80ff197d03db2a70c6a111f97dcdacad1b0babfa. The fix will be included in TensorFlow 2.11. We will also cherrypick this commit on TensorFlow 2.10.1, 2.9.3, and TensorFlow 2.8.4, as these are also affected and still in supported range.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-41899"
                },
                {
                    "source_name": "cwe",
                    "external_id": "CWE-20"
                },
                {
                    "source_name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-27rc-728f-x5w2",
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-27rc-728f-x5w2"
                },
                {
                    "source_name": "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sdca_internal.cc",
                    "url": "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sdca_internal.cc"
                },
                {
                    "source_name": "https://github.com/tensorflow/tensorflow/commit/80ff197d03db2a70c6a111f97dcdacad1b0babfa",
                    "url": "https://github.com/tensorflow/tensorflow/commit/80ff197d03db2a70c6a111f97dcdacad1b0babfa"
                },
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b2b5f2cd-49e6-4091-a0e0-c0bb71543e23": {
                    "extension_type": "property-extension",
                    "nvd_cve": {
                        "data_type": "CVE",
                        "data_format": "MITRE",
                        "data_version": "4.0",
                        "CVE_data_meta": {
                            "ID": "CVE-2022-41899",
                            "ASSIGNER": "security-advisories@github.com"
                        },
                        "problemtype": {
                            "problemtype_data": [
                                {
                                    "description": [
                                        {
                                            "lang": "en",
                                            "value": "CWE-20"
                                        }
                                    ]
                                }
                            ]
                        },
                        "references": {
                            "reference_data": [
                                {
                                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-27rc-728f-x5w2",
                                    "name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-27rc-728f-x5w2",
                                    "refsource": "CONFIRM",
                                    "tags": []
                                },
                                {
                                    "url": "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sdca_internal.cc",
                                    "name": "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sdca_internal.cc",
                                    "refsource": "MISC",
                                    "tags": []
                                },
                                {
                                    "url": "https://github.com/tensorflow/tensorflow/commit/80ff197d03db2a70c6a111f97dcdacad1b0babfa",
                                    "name": "https://github.com/tensorflow/tensorflow/commit/80ff197d03db2a70c6a111f97dcdacad1b0babfa",
                                    "refsource": "MISC",
                                    "tags": []
                                }
                            ]
                        },
                        "description": {
                            "description_data": [
                                {
                                    "lang": "en",
                                    "value": "TensorFlow is an open source platform for machine learning. Inputs `dense_features` or `example_state_data` not of rank 2 will trigger a `CHECK` fail in `SdcaOptimizer`. We have patched the issue in GitHub commit 80ff197d03db2a70c6a111f97dcdacad1b0babfa. The fix will be included in TensorFlow 2.11. We will also cherrypick this commit on TensorFlow 2.10.1, 2.9.3, and TensorFlow 2.8.4, as these are also affected and still in supported range."
                                }
                            ]
                        }
                    },
                    "configurations": {
                        "CVE_data_version": "4.0",
                        "nodes": []
                    },
                    "impact": {},
                    "publishedDate": "2022-11-18T22:15Z",
                    "lastModifiedDate": "2022-11-20T02:44Z"
                }
            }
        }
    ]
}