{
    "type": "bundle",
    "id": "bundle--e5e02cd7-8a71-4d29-9262-8d86d9c03466",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--bc249204-6e9a-4445-82c5-1c85b57c0693",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-11-09T20:15:00.000Z",
            "modified": "2022-11-10T14:29:00.000Z",
            "name": "CVE-2022-42964",
            "description": "An exponential ReDoS (Regular Expression Denial of Service) can be triggered in the pymatgen PyPI package, when an attacker is able to supply arbitrary input to the GaussianInput.from_string method",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-42964"
                },
                {
                    "source_name": "cwe",
                    "external_id": "NVD-CWE-Other"
                },
                {
                    "source_name": "https://research.jfrog.com/vulnerabilities/pymatgen-redos-xray-257184/",
                    "url": "https://research.jfrog.com/vulnerabilities/pymatgen-redos-xray-257184/"
                },
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b2b5f2cd-49e6-4091-a0e0-c0bb71543e23": {
                    "extension_type": "property-extension",
                    "nvd_cve": {
                        "data_type": "CVE",
                        "data_format": "MITRE",
                        "data_version": "4.0",
                        "CVE_data_meta": {
                            "ID": "CVE-2022-42964",
                            "ASSIGNER": "security@jfrog.com"
                        },
                        "problemtype": {
                            "problemtype_data": [
                                {
                                    "description": [
                                        {
                                            "lang": "en",
                                            "value": "NVD-CWE-Other"
                                        }
                                    ]
                                }
                            ]
                        },
                        "references": {
                            "reference_data": [
                                {
                                    "url": "https://research.jfrog.com/vulnerabilities/pymatgen-redos-xray-257184/",
                                    "name": "https://research.jfrog.com/vulnerabilities/pymatgen-redos-xray-257184/",
                                    "refsource": "MISC",
                                    "tags": [
                                        "Exploit",
                                        "Third Party Advisory"
                                    ]
                                }
                            ]
                        },
                        "description": {
                            "description_data": [
                                {
                                    "lang": "en",
                                    "value": "An exponential ReDoS (Regular Expression Denial of Service) can be triggered in the pymatgen PyPI package, when an attacker is able to supply arbitrary input to the GaussianInput.from_string method"
                                }
                            ]
                        }
                    },
                    "impact": {
                        "baseMetricV3": {
                            "cvssV3": {
                                "version": "3.1",
                                "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                                "attackVector": "NETWORK",
                                "attackComplexity": "LOW",
                                "privilegesRequired": "NONE",
                                "userInteraction": "NONE",
                                "scope": "UNCHANGED",
                                "confidentialityImpact": "NONE",
                                "integrityImpact": "NONE",
                                "availabilityImpact": "HIGH",
                                "baseScore": 7.5,
                                "baseSeverity": "HIGH"
                            },
                            "exploitabilityScore": 3.9,
                            "impactScore": 3.6
                        }
                    },
                    "publishedDate": "2022-11-09T20:15Z",
                    "lastModifiedDate": "2022-11-10T14:29Z"
                }
            }
        },
        {
            "type": "indicator",
            "spec_version": "2.1",
            "id": "indicator--437ef157-d4d7-4096-b04c-786dbcd72402",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-11-09T20:15:00.000Z",
            "modified": "2022-11-10T14:29:00.000Z",
            "name": "CVE-2022-42964",
            "description": "An exponential ReDoS (Regular Expression Denial of Service) can be triggered in the pymatgen PyPI package, when an attacker is able to supply arbitrary input to the GaussianInput.from_string method",
            "indicator_types": [
                "compromised"
            ],
            "pattern": "[(software:cpe='cpe:2.3:a:pymatgen:pymatgen:-:*:*:*:*:*:*:*')]",
            "pattern_type": "stix",
            "pattern_version": "2.1",
            "valid_from": "2022-11-09T20:15:00Z",
            "external_references": [
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ],
            "object_marking_refs": [
                "marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"
            ],
            "extensions": {
                "extension-definition--b463c449-d022-48b7-b464-3e9c7ec5cf16": {
                    "extension_type": "property-extension",
                    "all_cpe23uris": [
                        "cpe:2.3:a:pymatgen:pymatgen:-:*:*:*:*:*:*:*"
                    ],
                    "vulnerable_cpeid": [
                        "cpe:2.3:a:pymatgen:pymatgen:-:*:*:*:*:*:*:*"
                    ]
                }
            }
        },
        {
            "type": "relationship",
            "spec_version": "2.1",
            "id": "relationship--20b02b6e-48ad-45bf-a596-feee5b77dad7",
            "created_by_ref": "identity--748e6444-f073-4c50-b558-f49be8897a81",
            "created": "2022-11-09T20:15:00.000Z",
            "modified": "2022-11-10T14:29:00.000Z",
            "relationship_type": "identifies",
            "source_ref": "indicator--437ef157-d4d7-4096-b04c-786dbcd72402",
            "target_ref": "vulnerability--fffbf92a-6387-42f4-84b9-e1468edde7d0",
            "external_references": [
                {
                    "source_name": "cve2stix",
                    "description": "This object was created using cve2stix from the Signals Corps.",
                    "url": "https://github.com/signalscorps/cve2stix"
                }
            ]
        }
    ]
}